dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.1         # For camera scanning
  permission_handler: ^11.3.0     # To request camera permissions
  url_launcher: ^6.2.5            # To open scanned URLs

